kind: pipeline
type: docker
name: default

steps:
- name: build-amd64
  image: golang:1.12
  commands:
  - apt update && apt install ca-certificates libgnutls30 -y
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/linux/amd64/terraform-credentials-env
  when:
    event:
    - push
    - pull_request
    - tag

- name: artifacts-amd64
  image: golang:1.12
  commands:
  - tar -cvzf release/terraform-credentials-env_linux_amd64.tar.gz -C release/linux/amd64 terraform-credentials-env
  - sha256sum release/*.tar.gz > release/terraform-credentials-env_checksums.txt
  when:
    event:
    - push
    - tag
    
- name: build-arm64
  image: golang:1.12
  commands:
  - apt update && apt install ca-certificates libgnutls30 -y
  - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/linux/amd64/terraform-credentials-env
  when:
    event:
    - push
    - pull_request
    - tag

- name: artifacts-arm64
  image: golang:1.12
  commands:
  - tar -cvzf release/terraform-credentials-env_linux_arm64.tar.gz -C release/linux/arm64 terraform-credentials-env
  - sha256sum release/*.tar.gz >> release/terraform-credentials-env_checksums.txt
  when:
    event:
    - push
    - tag
- name: release
  image: plugins/github-release
  settings:
    files:
      - release/terraform-credentials-env_*.tar.gz
      - release/terraform-credentials-env_checksums.txt
    api_key:
      from_secret: api_key
  when:
    event: tag

trigger:
  ref:
    include:
    - refs/heads/master
    - refs/pull/**
    - refs/tags/**
